apiVersion: azmonitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: trivy-operator
  namespace: trivy-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: trivy-operator
      app.kubernetes.io/name: trivy-operator

  endpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      honorLabels: true

  namespaceSelector:
    matchNames:
      - trivy-system